pipeline {
    agent any

    environment {
        // Define environment variables
        TF_VAR_FILE = "terraform.tfvars"
        //TF_CLI_CONFIG_FILE = "$HOME/.terraformrc"
    }

    stages {
        stage('Terraform Init') {
            steps {
                // Initialize Terraform
		sh 'pwd'
		sh 'cd /home/apskarthickgmai/mygitrepos/mydevopsrepo/terraform'
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                // Run Terraform plan and save the output to a file
		sh 'pwd'
		sh 'cd /home/apskarthickgmai/mygitrepos/mydevopsrepo/terraform'
		sh 'terraform plan -out=tfplan'
            }
        }

        stage('Approve') {
            steps {
                // Wait for manual approval
                input message: 'Do you want to apply the changes?', ok: 'Apply'
            }
        }

        stage('Terraform Apply') {
            steps {
                // Apply the Terraform plan
		sh 'pwd'
		sh 'cd /home/apskarthickgmai/mygitrepos/mydevopsrepo/terraform'
                sh 'terraform apply "tfplan"'
            }
        }
    }

    post {
        always {
            // Clean up the workspace
            //cleanWs()
	    sh 'echo All done'
        }
    }
}
