pipeline {
    agent any

    environment {
        // Define environment variables
        TF_VAR_FILE = "terraform.tfvars"
        //TF_CLI_CONFIG_FILE = "$HOME/.terraformrc"
    }

    stages {
        stage('Terraform Init') {
            steps {
                // Initialize Terraform
		sh '''
		    pwd
      		    cd terraform
		    terraform init
		'''
            }
        }

        stage('Terraform Plan') {
            steps {
                // Run Terraform plan and save the output to a file
		sh '''
		   cd terraform
		   terraform plan -out=tfplan
     		'''
  		
            }
        }

        stage('Approve') {
            steps {
                // Wait for manual approval
                input message: 'Do you want to apply the changes?', ok: 'Apply'
            }
        }

        stage('Terraform Apply') {
            steps {
                // Apply the Terraform plan
		sh '''
		   cd terraform
                   terraform apply "tfplan"
		'''
            }
        }
    }

    post {
        always {
            // Clean up the workspace
            //cleanWs()
	    sh 'echo All done'
        }
    }
}
