apiVersion: v1
kind: Pod
metadata:
  name: apache-single-pod
  labels:
    app: apache-single
spec:
  containers:
  - name: httpd
    image: httpd
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
