# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # You can specify a port within the range 30000-32767 or let Kubernetes choose

